var goodsList = [
  {
    type: 1,
    name: "苹果",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/o.jpg"),
        title: "新鲜苹果约500g",
        desc: "新鲜水果|清甜多汁|口感脆爽",
        detail: "每颗苹果都经过精心挑选，保证新鲜度和口感，产地不同，果形大小略有差异，请理解。",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 7.99,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/y.jpg"),
        title: "崇明苹果350g/份",
        desc: "细脆多汁|天然甜美|适合生吃",
        detail: "崇明苹果以其细脆的口感和天然的甜味而著称，非常适合直接生吃，保留了水果的原汁原味。",
        orign: "上海市",
        condition: "冷藏",
        content: "350g",
        price: 9.89,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/p.png"),
        title: "大娃娃苹果约600g",
        desc: "果肉丰腴|清甜可口|营养丰富",
        detail: "大娃娃苹果果肉丰腴，清甜可口，含有丰富的营养成分，是健康生活的好选择。",
        orign: "云南省曲靖市",
        condition: "冷藏",
        content: "约600g",
        price: 5.2,
      },
      
    ],
},

  {
    type: 2,
    name: "香蕉",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/b.jpg"),
        title: "特大号香蕉 2根500g以上",
        desc: "果肉细腻|口感甜蜜|丰富维生素",
        detail: "新鲜的特大号香蕉，果肉细腻，口感甜蜜，含有丰富的维生素，营养丰富。",
        orign: "海南省东方市",
        condition: "冷藏",
        content: "500g以上",
        price: 14.8,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/goods2.jpg"),
        title: "有机香蕉 600g/份",
        desc: "有机栽培|香蕉口感|生熟两吃",
        detail: "采用有机栽培的香蕉，果实饱满，口感细腻，生熟皆宜，非常适合作为健康零食。",
        orign: "山东省德州市",
        condition: "冷藏",
        content: "600g",
        price: 8.9,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/c.jpg"),
        title: "新鲜香蕉 900g/份",
        desc: "新鲜采摘|果实饱满|口感清甜",
        detail: "新鲜采摘的香蕉，果实饱满，口感清甜，营养丰富，是家常鲜蔬中的一道佳品。",
        orign: "山东省潍坊市",
        condition: "冷藏",
        content: "900g",
        price: 4.99,
      },
      {
        id: "3",
        imgUrl: require("@/assets/img/goods/2fccd4b4a5ff3e96ef3a0f05cfb9fd03.jpg"),
        title: "特小号香蕉 300g以上",
        desc: "小巧精致|口感绵软|清甜可口",
        detail: "特小号香蕉，个头迷你，口感绵软，清甜可口，非常适合作为小零食或搭配其他食材食用。",
        orign: "山东省潍坊市",
        condition: "冷藏",
        content: "300g",
        price: 7.89,
      },
      {
        id: "4",
        imgUrl: require("@/assets/img/goods/n.jpg"),
        title: "[净菜]香蕉 200g/袋",
        desc: "低卡轻蔬|补充维C|一餐刚好",
        detail: "精选的香蕉，每袋200克，低卡轻蔬，富含维生素C，是一餐的理想搭配。",
        orign: "河北",
        condition: "冷藏",
        content: "200g",
        price: 6.9,
      },
    ],
},

{
  type: 3,
  name: "榴莲",
  info: [
    {
      id: "0",
      imgUrl: require("@/assets/img/goods/8.jpg"),
      title: "金枕头榴莲 750g/袋",
      desc: "榴莲果肉|香甜鲜美|口感细腻",
      detail: "金枕头榴莲，果肉香甜鲜美，口感细腻，是榴莲爱好者的最爱。",
      orign: "广东省湛江市",
      condition: "冷藏",
      content: "750g",
      price: 9.8,
    },
    {
      id: "1",
      imgUrl: require("@/assets/img/goods/0978a1cfec91778c34820969e0b8a093.jpeg"),
      title: "猫山王榴莲 360g/份",
      desc: "皮薄果肉|浓郁香甜|口感丰润",
      detail: "猫山王榴莲，皮薄果肉浓郁香甜，口感丰润，是榴莲界的顶级品种。",
      orign: "河北省保定市",
      condition: "冷藏",
      content: "360g",
      price: 9.5,
    },
    {
      id: "2",
      imgUrl: require("@/assets/img/goods/a57920e7e2f56f60d15c98264e698962.png"),
      title: "泰国榴莲 300g",
      desc: "泰国进口|香浓细腻|口感丰润",
      detail: "泰国进口榴莲，香浓细腻，口感丰润，给您带来异国风情的美味体验。",
      orign: "山东省临沂市",
      condition: "冷藏",
      content: "300g",
      price: 5.5,
    },
    {
      id: "3",
      imgUrl: require("@/assets/img/goods/e97a3c8daf219235a4c95b2893c99890.jpg"),
      title: "泰国榴莲 400g/份",
      desc: "泰国进口|鲜香浓郁|果肉饱满",
      detail: "泰国进口榴莲，鲜香浓郁，果肉饱满，带来正宗的泰式榴莲风味。",
      orign: "陕西省渭南市",
      condition: "冷藏",
      content: "400g",
      price: 6.99,
    },
  ],
},
{
  type: 4,
  name: "凤梨",
  info: [
    {
      id: "0",
      imgUrl: require("@/assets/img/goods/aa9246a2bed0f20d40646765eb3b3c30.jpg"),
      title: "[可即食] 凤梨布丁 400g/盒",
      detail: "选用新鲜凤梨制成的布丁，口感丝滑，香味浓郁，营养丰富。",
      orign: "河北石家庄",
      condition: "冷藏",
      content: "400g",
      desc: "口感丝滑|香味浓郁|营养丰富",
      price: 2.59,
    },
    {
      id: "1",
      imgUrl: require("@/assets/img/goods/12f288579be93c746acc13691031123a.jpg"),
      title: "[非转基因凤梨] 凤梨冰淇淋 180g/份",
      detail: "选用优质凤梨制成的冰淇淋，口感细腻，味道浓郁，清凉解暑。",
      orign: "河北石家庄",
      condition: "冷藏",
      content: "180g",
      desc: "口感细腻|味道浓郁|清凉解暑",
      price: 5.9,
    },
    {
      id: "2",
      imgUrl: require("@/assets/img/goods/385a70b28df5c97a7b7732cfe5b6bf2b.jpg"),
      title: "[非转基因凤梨] 凤梨酥 400g/份",
      detail: "凤梨果酱包裹在酥皮中，口感酥脆，香味浓郁，回味无穷。",
      orign: "河北石家庄",
      condition: "冷藏",
      content: "400g",
      desc: "口感酥脆|香味浓郁|回味无穷",
      price: 5.5,
    },
    {
      id: "3",
      imgUrl: require("@/assets/img/goods/c38d8b51a7990c176fcbbe39a67f7792.jpeg"),
      title: "凤梨酥饼 130g/袋",
      desc: "酥皮外衣|凤梨果馅|香甜可口",
      price: 5.9,
      detail: "外酥里软，凤梨果馅口感浓郁，香甜可口，是下午茶的好伴侣。",
      orign: "河北石家庄",
      condition: "冷藏",
      content: "130g",
    },
    {
      id: "4",
      imgUrl: require("@/assets/img/goods/5e35e4c7fcd3b506881972a0ef7d913f.jpg"),
      title: "凤梨蛋挞 120g/袋",
      desc: "酥皮蛋挞|凤梨口味|香甜可口",
      detail: "凤梨口味的蛋挞，酥皮香脆，凤梨馅醇厚，香甜可口，一口回味。",
      orign: "河北",
      condition: "冷藏",
      content: "120g",
      price: 6.8,
    },
  ],
},
{
  type: 5,
  name: "梨",
  info: [
    {
      id: "0",
      imgUrl: require("@/assets/img/goods/9d60d45d983087017f93aa85f5c1eaf8.jpeg"),
      title: "新鲜梨500g/份",
      desc: "清香脆甜|果肉饱满|口感丰富",
      detail: "新鲜梨，果肉清香脆甜，饱满多汁，口感丰富，是夏季水果的不可错过的选择。",
      orign: "江苏省苏州市",
      condition: "冷藏",
      content: "500g",
      price: 7.19,
    },
   
  ],
},
{
  type: 6,
  name: "芒果",
  info: [
    {
      id: "0",
      imgUrl: require("@/assets/img/goods/fd43fb8f3ec059bf8cc401001fb462f2.jpeg"),
      title: "进口芒果1个",
      detail: "香甜多汁|果肉细腻|口感醇厚",
      orign: "国外进口",
      condition: "常温",
      content: "1个",
      desc: "香甜多汁的进口芒果，果肉细腻，口感醇厚，是夏日水果的美味选择。",
      price: 19.89,
    },
   
  ],
},
{
  type: 7,
  name: "荔枝",
  info: [
    {
      id: "0",
      imgUrl: require("@/assets/img/goods/e922a4bb79b9386e87fe753050d597be.jpeg"),
      title: "新鲜荔枝500g/份",
      desc: "果肉鲜嫩|汁水丰富|清甜可口",
      detail: "新鲜荔枝，果肉鲜嫩，汁水丰富，口感清甜可口，是夏季水果中的一道美味佳肴。",
      orign: "云南省红河哈尼族彝族自治州",
      condition: "冷藏",
      content: "500g",
      price: 11.8,
    },
   
  ],
},
{
  type: 8,
  name: "车厘子",
  info: [
    {
      id: "0",
      imgUrl: require("@/assets/img/goods/4af4ab5f421711a4d3d3ce8fc2925f37.jpg"),
      title: "进口车厘子500g/份",
      desc: "果粒饱满|酸甜可口|营养丰富",
      detail: "进口车厘子，果粒饱满，酸甜可口，含有丰富的营养成分，是夏季的美味水果之一。",
      orign: "国外进口",
      condition: "冷藏",
      content: "500g",
      price: 29.99,
    },
   
  ],
},
];

export default goodsList;
